import "./navbar.scss";
import "./home.scss";
import "./devise.scss";
import "./component.scss";
import "./querys.scss";
import "./footer.scss";
import "./checkbox.scss";
import '@fortawesome/fontawesome-free/css/all.min.css'
import '@fortawesome/fontawesome-free/js/all.js'
import "tailwindcss/dist/tailwind.css"